### ISSUE TITLE
Rust GitHub Actions in actions-rs seem unmaintained

### ISSUE THREAD

**Issue by oherrala** [rustsec/audit-check#2]
This is not a Rust crate, but tooling used by many Rust projects. Is this correct place to discuss and maybe take action on informing community about the issue?

The `actions-rs` GitHub Actions from GitHub (https://github.com/actions-rs) is used by many Rust projects.

However, the actions don't see much love, there's discussion about the maintenance status here: https://github.com/actions-rs/meta/issues/43

As these actions are not maintained a known vulnerabilities might start to pile up and things might start to break because GitHub is deprecating support for some thing (e.g. https://github.com/actions-rs/audit-check/issues/227).

Pinging @svartalf since he's the (only?) owner of the GitHub organization.

**Comment by tarcieri** [comment]
I think we could probably put together a much simpler action for people to use, which doesn't depend on e.g. Node.js in any way

**Comment by jonasbb** [comment]
Some time ago, I wrote https://github.com/actions-rust-lang/audit to move off actions-rs. It is written as a composite action with the main logic in Python instead of JavaScript. It supports maintaining issues and writes a workflow summary with the findings. It doesn't really provide more features than audit-check except for an explicit input argument to ignore IDs.
I am happy to talk more about it in case you find it of any interest.

**Comment by pinkforest** [comment]
This action now uses node16 and dependencies have been bumped so should be perfectly usable.
It's fairly simple in the end - can continue altearntives in discussions if there is really need.
